doctrine:
    dbal:
        connections:
            default:
                wrapper_class: App\Packages\Common\Infrastructure\DbalConnection
                dbname: '%env(DATABASE_DEFAULT_DBNAME)%'
                user: '%env(DATABASE_DEFAULT_USER)%'
                password: '%env(DATABASE_DEFAULT_PASSWORD)%'
                host: '%env(DATABASE_DEFAULT_HOST)%'
                driver: '%env(DATABASE_DEFAULT_DRIVER)%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci