doctrine:
    dbal:
        connections:
            default:
                wrapper_class: App\Packages\Common\Infrastructure\DbalConnection
                dbname: '%env(DATABASE_DEFAULT_DBNAME)%'
                user: '%env(DATABASE_DEFAULT_USER)%'
                password: '%env(DATABASE_DEFAULT_PASSWORD)%'
                host: '%env(DATABASE_DEFAULT_HOST)%'
                driver: '%env(DATABASE_DEFAULT_DRIVER)%'