swiftmailer:
    username: '%env(APP_EMAIL_USERNAME)%'
    password: '%env(APP_EMAIL_PASSWORD)%'
    host: '%env(APP_EMAIL_HOST)%'
    port: '%env(APP_EMAIL_PORT)%'
    transport: '%env(APP_EMAIL_TRANSPORT)%'
    encryption: '%env(APP_EMAIL_ENCRYPTION)%'
