services:
    _defaults:
        autowire: true

    App\Packages\AccessManagement\Application\Query\AuthUserInformationByCredentialsQueryHandler:
        class: App\Packages\AccessManagement\Infrastructure\Query\DbalAuthUserInformationByCredentialsQueryHandler

    App\Packages\AccessManagement\Application\Query\AuthUserFactory: ~