services:
    _defaults:
        autowire: true

    App\Packages\AccessManagement\Application\Query\LoginInformationByUserCredentialsQueryHandler:
        class: App\Packages\AccessManagement\Infrastructure\Query\DbalLoginInformationByUserCredentialsQueryHandler

    App\Packages\AccessManagement\Application\Query\LoginInformationByUserIdQueryHandler:
        class: App\Packages\AccessManagement\Infrastructure\Query\DbalLoginInformationByUserIdQueryHandler

    App\Packages\AccessManagement\Application\Query\AuthUserFactory: ~