services:
    App\Api\WebApiV1\Endpoints:
        arguments: [!tagged 'api_v1.endpoint']

    App\Api\WebApiV1\RoutingLoader:
        class: App\Api\WebApiV1\RoutingLoader
        tags: ['routing.loader']
        public: true
        autowire: true

imports:
    - { resource: './endpoints.yaml' }