services:
    AppWebApiV1Bundle/Resources/EndpointConsumer:
        public: true
        autowire: false
        tags: ['controller.service_arguments']

imports:
    - { resource: '../../Endpoint/endpoints.yaml' }