services:
    _defaults:
        autowire: true

    App\Packages\UserMangement\Application\Command\CreateUser\UserFactory: ~
    App\Packages\UserMangement\Application\Command\CreateUser\CreateUserHandler:
        public: true

    App\Packages\UserMangement\Application\Command\CreateUser\RemoveUserHandler:
        public: true