services:
    _defaults:
        autowire: true

    App\Packages\UserManagement\Application\Command\CreateUser\UserFactory: ~

    App\Packages\UserManagement\Application\Command\CreateUser\CreateUserHandler:
        public: true

    App\Packages\UserManagement\Application\Resources\User\UserRepository:
        class: App\Packages\UserManagement\Infrastructure\User\DbalUserRepository

    App\Packages\UserManagement\Domain\User\UserValidator: ~

imports:
    - { resource: './imports/projections.yaml' }
    - { resource: './imports/fixtures.yaml' }