services:
    _defaults:
        autowire: true

    App\CLI\Fixtures\ExecuteCommand:
        tags: ['console.command']

    App\CLI\Fixtures\FixtureRepository:
        arguments: [!tagged 'app.fixture']

