services:
    _defaults:
        autowire: true

    App\Packages\UserMangement\Application\Resources\User\UserRepository:
        class: App\Packages\UserMangement\Infrastructure\User\DbalUserRepository

imports:
    - { resource: './src/Application/Command/services.yaml' }
    - { resource: './src/Installation/Fixtures/fixtures.yaml' }