services:
    _defaults:
        autowire: true

    App\Packages\UserManagement\Domain\Handlers\CreateUserHandler:
        public: true

    App\Packages\UserManagement\Domain\UserRepository: ~

    App\Packages\UserManagement\Domain\UserValidation\UserValidator: ~

    App\Packages\UserManagement\Domain\UserEventDispatcher: ~

    App\Packages\UserManagement\Domain\UserEventProjection:
        class: App\Packages\UserManagement\Infrastructure\DbalUserEventProjection

    App\Packages\UserManagement\Domain\UserValidation\UsersWithAnEqualValueQuery:
        class: App\Packages\UserManagement\Infrastructure\DbalUsersWithAnEqualValueQuery