services:
    _defaults:
        autowire: true

    App\Packages\UserManagement\Application\Query\UsersQueryHandler:
        class: App\Packages\UserManagement\Infrastructure\Query\DbalUsersQueryHandler

    App\Packages\UserManagement\Domain\Handlers\CreateUserHandler:
        public: true

    App\Packages\UserManagement\Domain\UserValidation\ExistingUsersByValuesQueryHandler:
        class: App\Packages\UserManagement\Infrastructure\Command\DbalExistingUsersByValuesQueryHandler

    App\Packages\UserManagement\Domain\UserEventDispatcher: ~

    App\Packages\UserManagement\Domain\UserEventProjection:
        class: App\Packages\UserManagement\Infrastructure\Command\DbalUserEventProjection