imports:
    - { resource: '../src/Packages/Common/services/prod.yaml' }
    - { resource: '../src/Packages/JobManagement/services/prod.yaml' }
    - { resource: '../src/Packages/UserManagement/services/prod.yaml' }
    - { resource: '../src/CLI/services/prod.yaml' }