imports:
    - { resource: '../src/Packages/Common/services/dev.yaml' }
    - { resource: '../src/Packages/JobManagement/services/dev.yaml' }
    - { resource: '../src/Packages/UserManagement/services/dev.yaml' }
    - { resource: '../src/CLI/services/dev.yaml' }