imports:
    - { resource: '../src/Packages/Common/_services/dev.yaml' }
    - { resource: '../src/Packages/JobQueuing/_services/dev.yaml' }
    - { resource: '../src/Packages/UserManagement/_services/dev.yaml' }
    - { resource: '../src/CLI/_services/dev.yaml' }