parameters:
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

imports:
    - { resource: '../src/Packages/Common/services.yaml' }
    - { resource: '../src/Packages/UserManagement/services.yaml' }