services:
    _defaults:
        autowire: true

    App\Packages\JobQueuing\Domain\Job\JobRepository: ~
    App\Packages\JobQueuing\Domain\Job\JobValidator: ~

    App\Packages\JobQueuing\Application\Command\CreateJob\CreateJobHandler:
        public: true

imports:
    - { resource: './imports/projections.yaml' }