services:
    _defaults:
        autowire: true

    App\Packages\Common\Application\CommandBus: ~
    App\Packages\Common\Domain\CommandHandler: ~
    App\Packages\Common\Domain\AuditLog\EventDispatcher: ~

    App\Packages\Common\Domain\StateManager:
        class: App\Packages\Common\Infrastructure\DbalStateManager

    App\Packages\Common\Infrastructure\DbalConnection:
        alias: 'doctrine.dbal.default_connection'

    App\Packages\Common\Installation\Fixtures\FixtureRepository:
        arguments: [!tagged 'app.fixture']

    App\Packages\Common\Domain\Mailing\Mailer:
        class: App\Packages\Common\Infrastructure\Mailing\SwiftMailerBridge

    App\Packages\Common\Domain\AuditLog\AuditLogProjection:
        class: App\Packages\Common\Infrastructure\AuditLog\DbalAuditLogProjection

    App\Packages\Common\Domain\JobQueuing\JobProjection:
        class: App\Packages\Common\Infrastructure\JobQueuing\DbalJobProjection

    App\Packages\Common\Domain\JobQueuing\JobExistsByIdQuery:
        class: App\Packages\Common\Infrastructure\JobQueuing\JobExistsByIdQuery