services:
    _defaults:
        autowire: true

    App\Packages\UserManagement\Application\CreateUserHandler:
        public: true

    App\Packages\UserManagement\Application\Resources\User\UserRepository:
        class: App\Packages\UserManagement\Infrastructure\User\DbalUserRepository

    App\Packages\UserManagement\Domain\UserValidation\UserValidator: ~

    App\Packages\UserManagement\Domain\UserValidation\UsersWithAnEqualValueQuery:
        class: App\Packages\UserManagement\Infrastructure\DbalUsersWithAnEqualValueQuery

    App\Packages\UserManagement\Domain\UserProjection:
        class: App\Packages\UserManagement\Infrastructure\DbalUserProjection

imports:
    - { resource: './imports/fixtures.yaml' }