services:
    _defaults:
        autowire: true

    App\Packages\Common\Installation\Migrations\MigrationRepository:
        arguments: [!tagged 'app.migration']

imports:
    - { resource: './imports/migrations.yaml' }