services:
    _defaults:
        autowire: true

    App\Packages\Common\Application\CommandBus: ~
    App\Packages\Common\Application\Authorization\RolesRepository: ~
    App\Packages\Common\Application\Authorization\UserFactory: ~
    App\Packages\Common\Application\DateTimeFactory: ~

    App\Packages\Common\Domain\EventDispatcher: ~

    App\Packages\Common\Application\StateManager:
        class: App\Packages\Common\Infrastructure\DbalStateManager

    App\Packages\Common\Domain\Event\EventDispatcher: ~

    App\Packages\Common\Application\Command\CommandHandlerRepository:
        arguments: [!tagged 'app.command_handler']

    App\Packages\Common\Domain\Event\ProjectionRepository:
        arguments: [!tagged 'app.event_projection']

    App\Packages\Common\Infrastructure\DbalConnection: '@doctrine.dbal.default_connection'

    App\Packages\Common\Installation\Fixtures\FixtureRepository:
        arguments: [!tagged 'app.fixture']

imports:
    - { resource: './imports/projections.yaml' }