services:
    _defaults:
        autowire: true

    App\Packages\Common\Application\CommandBus: ~
    App\Packages\Common\Application\Authorization\RolesRepository: ~
    App\Packages\Common\Application\Authorization\UserFactory: ~

    App\Packages\Common\Domain\EventManager: ~
    App\Packages\Common\Application\StateManager:
        class: App\Packages\Common\Infrastructure\DbalStateManager

    App\Packages\Common\Infrastructure\DbalConnection: '@doctrine.dbal.default_connection'