services:
    _defaults:
        autowire: true

    App\Packages\Common\Application\StateManager:
        class: App\Packages\Common\Infrastructure\DbalStateManager

    App\Packages\Common\Infrastructure\DbalConnection: '@doctrine.dbal.default_connection'